name: "Helm Upgrade"
author: DevOps
description: Helm Upgrade

inputs:
  namespace:
    description: Kubernetes Namespace
    required: true
  base-chart:
    description: Chart to begin with.
    required: true
  values-file:
    description: Location of values file for helm chart.
    required: true
  additional-values:
    description: Comma seperated string that contains extra values set for helm.
    required: true
  additional-args:
    description: handles inline options such as atomic, or timeout.
    required: false
  release-name:
    description: Name of Release 
    required: false
    default: us-east-1
  problems-timeout:
    description: Number of seconds to wait before checking potential issues (as an integer of seconds). Adding a value enables problem detection.
    required: false

runs:
  using: "composite"
  steps:
    - id: helm-upgrade-action
      env:
        INPUT_NAMESPACE: ${{ inputs.namespace }}
        INPUT_BASE_CHART: ${{ inputs.base-chart }}
        INPUT_VALUES_FILE: ${{ inputs.values-file }}
        INPUT_ADDITIONAL_VALUES: ${{inputs.additional-values }}
        INPUT_ADDITIONAL_ARGS: ${{inputs.additional-args }}
        INPUT_RELEASE_NAME: ${{ inputs.release-name }}
        INPUT_PROBLEMS_TIMEOUT: ${{ inputs.problems-timeout }}
      run: ${{ github.action_path }}/action.sh
      shell: bash

