name: Test k6-test-action
on: 
  push:
    branches:
      - "*"
      - "!main"
  workflow_dispatch:

jobs:
  test-action:
    name: Test helm-upgrade-action
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install Kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.10.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/bin/kind
          kind create cluster

      - name: Pull Down Public Helm
        id: pull-down-public-helm
        run: | 
          helm create testchart

      - name: Run helm-upgrade-action
        uses: ./
        id: helm-upgrade-action
        with:
          region: true
          aws-account-id: 123456123456
          namespace: default
          base-chart: ./testchart
          values-file: ./values.yaml
          additional-values: "serviceAccount.create=false,awsAccountName=development,awsAccountNumber=123456123456,ecrTag=${{ github.sha }}"
          release-name: crazy-test

      - name: Test for Successful Helm Upgrade/Install
        id: helm-upgrade-test
        env:
          release-name: crazy-test
          namespace: default
          base-chart: ./testchart
        run: | 
          echo ${env.base-chart//.}
          chartname = "${{ env.release-name }}-${env.base-chart//.}"
          status=$(kubectl get pod -l app=$chartname -n ${{ env.namespace }} -o jsonpath="{.items[*]['status.phase']}")
           if [[ "$status"  == "Running" ]]; then
              echo "✅ Helm uploaded correctly, test pod is running."
              exit 0
          else
              echo "❌ Helm upload failed, test pod is not running."
              exit 1
          fi
